version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      - postgresql
    restart: on-failure

  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    ports: 
        - "80:80"
        - "443:443"
    depends_on:
        - web
